/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/addItemBirdScreen`; params?: Router.UnknownInputParams; } | { pathname: `/addItemBoltScreen`; params?: Router.UnknownInputParams; } | { pathname: `/addItemDeliveryScreen`; params?: Router.UnknownInputParams; } | { pathname: `/addItemLimeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/addItemLinkScreen`; params?: Router.UnknownInputParams; } | { pathname: `/addItemMechanicScreen`; params?: Router.UnknownInputParams; } | { pathname: `/addItemRidemoviScreen`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/loginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/turnoHomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/addItemBirdScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/addItemBoltScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/addItemDeliveryScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/addItemLimeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/addItemLinkScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/addItemMechanicScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/addItemRidemoviScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/loginScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/turnoHomeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/addItemBirdScreen${`?${string}` | `#${string}` | ''}` | `/addItemBoltScreen${`?${string}` | `#${string}` | ''}` | `/addItemDeliveryScreen${`?${string}` | `#${string}` | ''}` | `/addItemLimeScreen${`?${string}` | `#${string}` | ''}` | `/addItemLinkScreen${`?${string}` | `#${string}` | ''}` | `/addItemMechanicScreen${`?${string}` | `#${string}` | ''}` | `/addItemRidemoviScreen${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/loginScreen${`?${string}` | `#${string}` | ''}` | `/turnoHomeScreen${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/addItemBirdScreen`; params?: Router.UnknownInputParams; } | { pathname: `/addItemBoltScreen`; params?: Router.UnknownInputParams; } | { pathname: `/addItemDeliveryScreen`; params?: Router.UnknownInputParams; } | { pathname: `/addItemLimeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/addItemLinkScreen`; params?: Router.UnknownInputParams; } | { pathname: `/addItemMechanicScreen`; params?: Router.UnknownInputParams; } | { pathname: `/addItemRidemoviScreen`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/loginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/turnoHomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
